### ISSUE TITLE
1차시: 도메인 모델 시작하기

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#1]
1차시: 도메인 모델 시작하기

**Comment by phjppo0918** [comment]
1주차 과제 제출합니다!
https://why-doing.tistory.com/130

**Comment by gksdudrb922** [comment]
1차시 과제 제출합니다!
https://gksdudrb922.tistory.com/276

**Comment by changu100** [comment]
1주차 과제 진행중입니다! 
https://sosohanchan.tistory.com/65

**Comment by seong-wooo** [comment]
1차시 과제 제출합니다!
https://seongwoo-memo.notion.site/43ba719c3fb641a68f84804888627d90?pvs=4

**Comment by tigermint** [comment]
1주차 과제 제출합니다!
https://enchanted-vulture-720.notion.site/edda4f95cab34144a2f7dd466325d037?pvs=4

**Comment by sebin1213** [comment]
1주차 과제 제출합니다!
https://velog.io/@hope1213/DDD-1
