### ISSUE TITLE
2차시: 아키텍처 개요

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#2]
2차시: 아키텍처 개요

**Comment by phjppo0918** [comment]
2주차 과제 제출합니다!
https://why-doing.tistory.com/131

**Comment by gksdudrb922** [comment]
2주차 과제 제출합니다!
https://gksdudrb922.tistory.com/281

**Comment by seong-wooo** [comment]
2주차 과제 제출합니다!
https://www.notion.so/seongwoo-memo/2-6a99f9c0bf274309b3a3d1bb0b6f5ce2?pvs=4

2주차 질문 목록입니다.
### 궁금증 1

현재 프로젝트에서 웹소켓에서 STOMP를 사용한다. STOMP는 메시지큐 pub, sub을 활용한다.

표현 계층에서 응용 계층으로 요청을 전달하고, 응용 계층에서 요청을 응답한 결과를 통해 표현 계층에서 메시지 큐로 전달하는 방식으로 로직을 구현하고 있다.

- 이 메시지 큐를 인프라스트럭쳐의 영역으로 보고, 응용 계층 내부로 옮기는 것이 좋을까요?

**Comment by sebin1213** [comment]
2주차 과제 제출합니다!
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-2%EC%9E%A5

**Comment by changu100** [comment]
2주차 과제 제출해요!! 늦어서 죄송합니다
https://sosohanchan.tistory.com/66

**Comment by tigermint** [comment]
과제 제출합니다! 늦어서 죄송합니다
https://enchanted-vulture-720.notion.site/Ch2-610f4109c6f84961968346b93ed9e065?pvs=4
