### ISSUE TITLE
3차시: 애그리거트

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#3]
3차시: 애그리거트

**Comment by phjppo0918** [comment]
3주차 과제 제출합니다!
https://why-doing.tistory.com/139

**Comment by gksdudrb922** [comment]
3주차 과제 제출합니다!
https://gksdudrb922.tistory.com/286

**Comment by seong-wooo** [comment]
3주차 과제 제출합니다!
https://seongwoo-memo.notion.site/3-ba92b9fc18324a6b9db39453baaf5aa4?pvs=4

**Comment by sebin1213** [comment]
늦어서 죄송합니다.. 3주차 과제 제출합니다..
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-3%EC%9E%A5

**Comment by tigermint** [comment]
과제 제출합니다!
https://enchanted-vulture-720.notion.site/Ch3-761bd4dcfb3b447d86c6a9b2989d38a6?pvs=4

**Comment by changu100** [comment]
늦어서 죄송합니다.
https://sosohanchan.tistory.com/67
