### ISSUE TITLE
4차시: 리포지터리와 모델 구현

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#4]
4차시: 리포지터리와 모델 구현

**Comment by phjppo0918** [comment]
4주차 제출합니다!

https://why-doing.tistory.com/142

**Comment by gksdudrb922** [comment]
4주차 제출합니다!
https://gksdudrb922.tistory.com/289

**Comment by changu100** [comment]
4주차 제출해요~~
https://sosohanchan.tistory.com/68

**Comment by sebin1213** [comment]
4주차 제출합니다..!
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-4%EC%9E%A5

**Comment by seong-wooo** [comment]
4주차 제출합니다.!
https://seongwoo.oopy.io/47e1b47c-8fad-4d18-b21b-49ed4e6224e9

**Comment by tigermint** [comment]
4주차 제출합니다 .. 늦어서 죄송합니다
https://enchanted-vulture-720.notion.site/Ch4-6acb238370044d1888d70fb90cd4387c?pvs=4
