### ISSUE TITLE
5차시: 스프링 데이터 JPA를 이용한 조회 기능

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#5]
5차시: 스프링 데이터 JPA를 이용한 조회 기능

**Comment by seong-wooo** [comment]
제출합니다! https://seongwoo-memo.notion.site/5-JPA-555d7c07cf444411a365f8f003c1a304?pvs=4

**Comment by sebin1213** [comment]
5주차 제출합니다
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-5%EC%9E%A5

**Comment by phjppo0918** [comment]
5주차 제출합니다!
https://why-doing.tistory.com/144

**Comment by changu100** [comment]
5주차 제출해요
https://sosohanchan.tistory.com/70]]

너무 늦어버렷네요 미안합니다

**Comment by tigermint** [comment]
5주차 제출합니다! 늦어서 죄송합니다
https://enchanted-vulture-720.notion.site/Ch5-JPA-2ab7c58a847e4b89bae4a8add351b918?pvs=4

**Comment by gksdudrb922** [comment]
https://gksdudrb922.tistory.com/292
