### ISSUE TITLE
6차시: 응용 서비스와 표현 영역

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#6]
6차시: 응용 서비스와 표현 영역

**Comment by phjppo0918** [comment]
제출합니다!
https://why-doing.tistory.com/145

**Comment by gksdudrb922** [comment]
과제제출합니다!
https://gksdudrb922.tistory.com/293

**Comment by seong-wooo** [comment]
제출합니다~
https://seongwoo.oopy.io/fe76120f-fb57-48a6-be82-8e53c0a914f2

**Comment by changu100** [comment]
제출합니다~~
https://sosohanchan.tistory.com/71
논의하고싶은게 있어요 

1. 표현영역은 Controller 를 포함한다. 그렇다면 message queue 에서 Consumer는 표현영역일까? 아니면 다른 영역일까?
2. 응용 서비스에서 애그리거트 자체를 리턴하면 코딩은 편할 수 있지만 도메인의 로직 실행을 응용 서비스와 표현 영역 두곳에서 할 수 있게 된다. 동일하게 p213 - @PostMapping에서 파라미터로 가져온 값을 application 계층이 알고있어도 무방한가?

**Comment by sebin1213** [comment]
너무 늦었습니다... 죄송합니다 ㅠ
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-6%EC%9E%A5

**Comment by tigermint** [comment]
너무 늦어서 죄송합니다 ..
https://enchanted-vulture-720.notion.site/Ch6-2eb3dae4e87140e19f07c3d428aca902?pvs=4
