### ISSUE TITLE
7차시: 도메인 서비스

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#7]
7차시: 도메인 서비스

**Comment by phjppo0918** [comment]
제출합니다!

https://why-doing.tistory.com/146

**Comment by gksdudrb922** [comment]
제출합니다!
https://gksdudrb922.tistory.com/294

**Comment by changu100** [comment]
제출합니다.
https://sosohanchan.tistory.com/72
이번주는 엄청 짧네요!!

**Comment by sebin1213** [comment]
저번주 과제 제출합니다..!
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-7%EC%9E%A5

**Comment by seong-wooo** [comment]
저번주 과제 제출합니다. 늦어서 죄송합니다.
https://seongwoo-memo.notion.site/7-6cecd344f40e4b7b81f7b35889cba3f7?pvs=4
