### ISSUE TITLE
8차시: 애그리거트 트랜잭션 관리

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#8]
8차시: 애그리거트 트랜잭션 관리

**Comment by phjppo0918** [comment]
제출합니다!

https://why-doing.tistory.com/147

**Comment by changu100** [comment]
https://sosohanchan.tistory.com/73
제출해요 !!

**Comment by sebin1213** [comment]
https://velog.io/@hope1213/DDD-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-8%EC%9E%A5

**Comment by seong-wooo** [comment]
https://seongwoo-memo.notion.site/8-c043f428e5994a3096efcec89499c4df?pvs=4
제출합니다!

**Comment by gksdudrb922** [comment]
https://gksdudrb922.tistory.com/298
