### ISSUE TITLE
9차시: 도메인 모델과 바운디드 컨텍스트

### ISSUE THREAD

**Issue by gksdudrb922** [gksdudrb922/ddd-study#9]
9차시: 도메인 모델과 바운디드 컨텍스트

**Comment by phjppo0918** [comment]
제출합니다!
https://why-doing.tistory.com/160

**Comment by changu100** [comment]
https://sosohanchan.tistory.com/74
제출합니다!

**Comment by gksdudrb922** [comment]
제출합니다!
https://gksdudrb922.tistory.com/299

**Comment by seong-wooo** [comment]
제출합니다 ~
https://seongwoo-memo.notion.site/9-5dbd5cc239574e1c8de25f60334efd29?pvs=4

**Comment by tigermint** [comment]
제출합니다!
https://enchanted-vulture-720.notion.site/Ch9-b0ff99fa81734d9dbf99e2b083ad23b2?pvs=4
